### PR TITLE
Add files via upload & Custom images doc

### PR DESCRIPTION
**Pull request by louis-zepl**

### CODE REVIEW

**Review by BryanKatis — COMMENTED** [review]
I'd remove customer names from the image, i.e. Merkle

**Review by BryanKatis — CHANGES_REQUESTED** [review]
The '** Failed **' text wraps which doesn't look good

**Review by louis-zepl — COMMENTED** [review]
I want to add new files but I don't know how

**Review by louis-zepl — COMMENTED** [review]
Did my best to remove any text squashing & customer names

**Review by BryanKatis — APPROVED** [review]
Looks good!

**Review by zshainsky — APPROVED** [review]

**Pull request merged**
