### PR TITLE
[ZEPL-2654] User doc for revision

### PR DESCRIPTION
**Pull request by 1ambda**
image

image

image

image

### CODE REVIEW

**Comment by 1ambda** [comment]
/ping @sejunra Please help to review this PR in terms of expressions and grammar things.

**Comment by sejunra** [comment]
Can we change: 
4. ...ZEPL creates notebook versions automatically for the notebook. (periodically)...
to
4. ...ZEPL creates notebook versions automatically (at short time intervals)...

besides the above, LGTM.

**Review by sejunra — CHANGES_REQUESTED** [review]
Can we change:
4. ...ZEPL creates notebook versions automatically for the notebook. (periodically)...
to
4. ...ZEPL creates notebook versions automatically (at short time intervals)...

besides the above, LGTM.

**Comment by 1ambda** [comment]
Will merge if no more discussion.

**Comment by 1ambda** [comment]
resolved the conflict. and will merge.

**Pull request merged**
