### PR TITLE
[ZEPL-5396] Add page for snowflake

### PR DESCRIPTION
**Pull request by minahlee**
This is how the snowflake doc page will look:
screencapture-localhost-8000-guide-datasource-snowflake-2019-06-26-14_55_06

### CODE REVIEW

**Comment by kaizepl** [comment]
@minahlee I noticed a few grammatical issues in the first few paragraphs so it will be easier for me to check out the file and make the changes as opposed to commenting on them in GitHub.

**Comment by minahlee** [comment]
@kaizepl, thank you that would be great. You can push commits directly to this branch.

**Comment by kaizepl** [comment]
What's the easiest way for me to update the file? If it's in a PR then I
wouldn't be able to update my local checkout with it yet right?

Is there a way I can edit in direclty in GitHub?


Best Regards,


Ken Ibrahim

*Solutions Architect |* www.zepl.com

408-883-8250

**Comment by minahlee** [comment]
You can checkout this branch and edit file.

```
# check if your remote origin set correctly
git remote -v #should print below two line
# origin	git@github.com:ZEPL/zepl-documentation.git (fetch)
# origin	git@github.com:ZEPL/zepl-documentation.git (push)
# if not, run below command line
git set-url git@github.com:ZEPL/zepl-documentation.git

git fetch origin
git checkout docs/ZEPL-5396_snowflake
# make change in files
git add .
git commit -m "commit message"
git push origin docs/ZEPL-5396_snowflake
```

**Comment by kaizepl** [comment]
I've made my corrections.

**Review by kaizepl — APPROVED** [review]
I've made my corrections.

**Comment by minahlee** [comment]
Thank you so much @kaizepl!

**Pull request merged**
